# Generated by Django 3.0.1 on 2019-12-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190122_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='member_type',
            field=models.CharField(choices=[('1', 'Org'), ('2', 'Driver')], max_length=50),
        ),
    ]
